version: "2.1"
 
services:

  reverse-proxy:
    image: reverse-proxy:$VERSION_PROXY
    #build: "https://git.scimetis.net/yohan/docker-reverse-proxy.git"
    restart: always
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - reverse-proxy
    volumes:
      - /mnt/volumes/reverse-proxy_conf/data:/etc/apache2/sites-available:Z
      - /mnt/volumes/reverse-proxy_conf_enabled/data:/etc/apache2/sites-enabled:Z
      - /mnt/volumes/reverse-proxy_letsencrypt/data:/etc/letsencrypt:Z
 
  cron:
    image: cron:$VERSION_CRON
    #build: "https://git.scimetis.net/yohan/docker-cron.git"
    restart: always
    network_mode: "host"
    volumes:
      - ./crontab:/etc/crontab:Z
 
networks:

  reverse-proxy:
    external: true
